inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'haml-spec/**/*'

Lint/HandleExceptions:
  Exclude:
    # Ignore LoadError
    - 'lib/faml.rb'
    - 'lib/faml/tilt.rb'
Lint/Eval:
  Exclude:
    - 'spec/spec_helper.rb'

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/CaseEquality:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/GlobalVars:
  Exclude:
    - '**/extconf.rb'

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'

Style/IfUnlessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SignalException:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/TrailingWhitespace:
  Exclude:
    - 'spec/render/multiline_spec.rb'

Style/UnneededPercentQ:
  Enabled: false  # buggy
